config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  resources :posts do
  	resources :comments
  end
  resources :customers, only: [ :index ]
  root 'dashboard#index'
  get "angular_test", to: "angular_test#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_search_term.rb
class CustomerSearchTerm
	attr_reader :where_clause, :where_args, :order
	def initialize(search_term)
		search_term = search_term.downcase
		@where_clause = ""
		@where_args = {}
		if search_term =~ /@/
			build_for_email_search(search_term)
		else
			build_for_name_search(search_term)
		end
	end

	def build_for_name_search(search_term)
		@where_clause << case_insensitive_search(:first_name)
		@where_args[:first_name] = starts_with(search_term)
		@where_clause << " OR #{case_insensitive_search(:last_name)}"
		@where_args[:last_name] = starts_with(search_term)
		@order = "last_name asc"
	end
	def starts_with(search_term)
		search_term + "%"
	end
	def case_insensitive_search(field_name)
		"lower(#{field_name}) like :#{field_name}"
	end
	def extract_name(email)
		email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
	end


	def build_for_email_search(search_term)
		@where_clause << case_insensitive_search(:first_name)
		@where_args[:first_name] = starts_with(extract_name(search_term))
		@where_clause << " OR #{case_insensitive_search(:last_name)}"
		@where_args[:last_name] = starts_with(extract_name(search_term))
		@where_clause << " OR #{case_insensitive_search(:email)}"
		@where_args[:email] = search_term
		@order = "lower(email) = " +
		ActiveRecord::Base.connection.quote(search_term) +
		" desc, last_name asc"
	end
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates_presence_of :title;
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def new
		@post.comments.create! comments.params
		redirect_to @post
	end
	def create
		@post.comments.create! comments.params
		redirect_to @post
	end

	private
		def set_post
			@post = Post.find(params[:post_id])
		end

		def comments_params
			params.required(:comment).permit(:body)
		end
end

app/controllers/customers_controller.rb
# class CustomersController < ApplicationController
# 	def index
# 		@customers = Customer.all.limit(10)
# 	end
# end
class CustomersController < ApplicationController
	PAGE_SIZE = 3
	def index
		@page = (params[:page] || 0).to_i
		if params[:keywords].present?
			@keywords = params[:keywords]
			customer_search_term = CustomerSearchTerm.new(@keywords)
			 @customers = Customer.where(
			 customer_search_term.where_clause,
			 customer_search_term.where_args).
			 order(customer_search_term.order).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)

		else
			@customers = Customer.all().offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
			
		end

		respond_to do |format|
			format.html {}
			format.json { render json: @customers }
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
	<header>
		<h1 ng-if="name">Hello,{{name}}</h1>
	</header>
	<section>
		<form class="form-inline">
			<div class="form-group">
				<label for="name">Name</label>
				<input class="form-control" name="name" type="text" placeholder="Enter your name" autofocus ng-model="name">
			</div>
		</form>
	</section>
</article>

app/views/comments/_comment.html.erb
<p><%= comment.body %> -- <%= comment.created_at.to_s(:long) %></p>  

app/views/comments/_new.html.erb
<%= form_for([@post	, Comment.new], remote: true) do |f| %>	Your comment:<br>
	<%= f.text_area :body, size: '50*30' %><br>
	<%= f.submit "Leave Comment" %>
<% end %>

app/views/customers/_pager.html.erb
<div style="">	
	<span class="previous">
		<a href="" ng-click="previousPage()">&larr; Previous</a>
	</span>&nbsp;&nbsp;&nbsp;
	 <span class="next">
	 	<a href="" ng-click="nextPage()">Next &rarr;</a>
	</span>
</div>

app/views/customers/index.html.erb
<header>
	<h1 class="h2">Customer Search</h1>
	<%= link_to 'dashboard', root_path %>

</header>
<article ng-app="customers" ng-controller="CustemerSearchController">
	<section class="search-form">
		<form>
			<div class="input-group input-group-lg">
				<label for="keywords" class="sr-only">Keywords</label>
				<input type="text" name="keywords" class="form-control input-lg" placeholder="First Name, Last Name, or Email Address" ng-model="keywords">
				<span class="input-group-btn">
				<button class="btn btn-primary btn-lg" ng-click="search(keywords)">
				Find Customers
				</button>
				</span>
			</div>
		</form>
		<h1 class="searchedFor" ng-if="searchedFor">
	 
			<small>Searched for:</small> {{searchedFor}}
		
		
		</h1>

	</section>

	<section class="search-results">
		<header>
			<h1 class="h3">Results</h1>
		</header>
	
		<ol class="list-group">
		 	<li class="list-group-item clearfix" ng-repeat="customer in customers">
				<h3 class="pull-right">
				<small class="text-uppercase">Joined</small>
				{{ customer.created_at | date }}
						</h3>
				<h2 class="h3"> {{ customer.first_name }} {{ customer.last_name }}
				<small>{{ customer.username }}</small>
				</h2>
				<h4>{{ customer.email }}</h4>
			</li>
		</ol>
		
	</section>
	<%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
</article>
<script>

</script>

app/views/dashboard/index.html.erb
<header>
	<h1>
	Welcome to Shine, <%= current_user.email %>
	</h1>
	<h2>
	We're using Rails <%= Rails.version %>
	</h2>
</header>
<div>
	<%=link_to "Posts",posts_path %>
	<%=link_to "Customers",customers_path %>

</div>
<section>
	<p>
	Future home of Mysite's Dashboard
	</p>
	<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  	<% if notice.present? %>
  		<aside class="alert alert-info">
  			<%= notice %>
  		</aside>
  	<% end %>
  	<% if alert.present? %>
  		<aside class="alert alert-danger">
  			<%= alert %>
  		</aside>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,class:"form-control", id: :post_title %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body,class:"form-control", id: :post_body %>
  </div>

  
    <%= form.submit class:"btn btn-primary btn-lg" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'dashboard', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<h2>Comments</h2>
	<div id="comments">
		<%= render @post.comments %>
	</div>
<%= render 'comments/new',post: @post %>
<br>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>